# .air.toml
root = "."        # Specifies the project root directory to watch
tmp_dir = "tmp"   # Temporary directory for compiled binaries

[build]
# Command to build your Go application - now explicitly building to .exe
cmd = "go build -o ./tmp/main.exe ."
# Path to the compiled binary - now explicitly .exe
bin = "./tmp/main.exe"
log = "build-errors.log"         # Log file for build errors
include_ext = ["go", "html"]     # Include .go and .html extensions for watching
exclude_dir = ["tmp", "node_modules", "vendor"] # Directories to ignore
delay = 100                      # Delay before restarting (in milliseconds)

[run]
# No change needed here, as `air` automatically runs the `bin` specified above.
# Just ensure your binary path in `bin` correctly points to the .exe.