import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/header';
import HomeHero from '@/components/home-hero';
import NavigationTabs from '@/components/navigation-tabs';

export const metadata: Metadata = {
    title: 'Programming Pares Official Community',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="antialiased">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    disableTransitionOnChange
                >
                    <Header />
                    <main className="pb-12">
                        <div>
                            <HomeHero />
                            <div className="container px-12 mx-auto space-y-5">
                                <NavigationTabs />

                                {children}
                            </div>
                        </div>
                    </main>
                </ThemeProvider>
            </body>
        </html>
    );
}
